image: Visual Studio 2019  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - yarn install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build:prod   # команда сборки

test_script:
  - yarn lint  # скрипт линтования
